### ISSUE TITLE
specifying Jira version at build?

### ISSUE THREAD

**Issue by adehad** [Addono/docker-jira-software-standalone#5]
Hi @Addono !

Working on https://github.com/pycontribs/jira/pull/1079 a question has been raised about running multiple version in a pipeline.
I see from #3  we can set the env variable, do you know how we can do this dynamically?

I've done a brief look and I'm not sure we can set this without using a build arg to set the default value? (https://vsupalov.com/docker-build-pass-environment-variables/#option-2-setting-dynamic-env-values)

This should mean the workflow is unaffected for people using `docker run`, but someone could `docker build` and specify a build arg, should they want to use a specific version?

FYI @manc-lx

**Comment by Addono** [comment]
Hi!

This image does most of the building at startup - we do that to get a fresh license from Atlassian. So, you're completely fine with dynamically setting the environment variable at runtime.

Under the hood it uses the [`atlas-run` command](https://developer.atlassian.com/server/framework/atlassian-sdk/atlas-run/), which has a `--version` parameter you can use to ask for a specific version.

E.g. what just worked for me:
```bash
docker run --rm -it -p 2990:2990 --name jira addono/jira-software-standalone --version 8.17.1
```
